### PR TITLE
Set higher default and allow configuring puppeteer protocol timeout

### LINKED ISSUE #104: UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Promise was collected
Once **all tests finish successfully** this exception occurs on the CI:

`
W20200612-14:11:02.429(0)? (STDERR) (node:642) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Promise was collected
W20200612-14:11:02.429(0)? (STDERR)     at Promise (/home/jenkins/humly-home/packages/hrm/node_modules/puppeteer/lib/Connection.js:183:56)
W20200612-14:11:02.429(0)? (STDERR)     at new Promise (<anonymous>)
W20200612-14:11:02.429(0)? (STDERR)     at CDPSession.send (/home/jenkins/humly-home/packages/hrm/node_modules/puppeteer/lib/Connection.js:182:12)
W20200612-14:11:02.429(0)? (STDERR)     at ExecutionContext._evaluateInternal (/home/jenkins/humly-home/packages/hrm/node_modules/puppeteer/lib/ExecutionContext.js:107:44)
W20200612-14:11:02.429(0)? (STDERR)     at ExecutionContext.evaluateHandle (/home/jenkins/humly-home/packages/hrm/node_modules/puppeteer/lib/ExecutionContext.js:57:17)
W20200612-14:11:02.430(0)? (STDERR)     at ExecutionContext.<anonymous> (/home/jenkins/humly-home/packages/hrm/node_modules/puppeteer/lib/helper.js:112:23)
W20200612-14:11:02.430(0)? (STDERR)     at WaitTask.rerun (/home/jenkins/humly-home/packages/hrm/node_modules/puppeteer/lib/DOMWorld.js:570:65)
W20200612-14:11:02.430(0)? (STDERR)     at <anonymous>
W20200612-14:11:02.430(0)? (STDERR)     at process._tickDomainCallback (internal/process/next_tick.js:229:7)
W20200612-14:11:02.430(0)? (STDERR)  => awaited here:
W20200612-14:11:02.430(0)? (STDERR)     at Function.Promise.await (/home/jenkins/.meteor/packages/promise/.0.11.2.1bomg6e.mbyx++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20200612-14:11:02.430(0)? (STDERR)     at Promise.asyncApply (packages/meteortesting:browser-tests/browser/puppeteer.js:64:5)
W20200612-14:11:02.430(0)? (STDERR)     at /home/jenkins/.meteor/packages/promise/.0.11.2.1bomg6e.mbyx++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20200612-14:11:02.430(0)? (STDERR) (node:642) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
W20200612-14:11:02.431(0)? (STDERR) (node:642) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 
Too long with no output (exceeded 1m0s): context deadline exceeded
`

After the investigation, I have found out that this is caused by unit tests using enzyme' shallow rendering. Once I remove these tests everything is fine, but I can't find anything wrong in them.
Also, this exception occurs every once in a few runs (2 - 3). Here is the typical unit test that makes this issue happen:

`
import React from "react";
import { expect } from "chai";
import { shallow, configure } from "enzyme";
import Adapter from "enzyme-adapter-react-16";
// import sinon from "sinon";

import ExampleView from "./ExampleView";

configure({ adapter: new Adapter() });

const defaultProps = {
    name: "test name",
    text: "test value",
};

describe(".../ExampleView", () => {
    before(() => {
        // methods stubs
    });

    after(() => {
        // restores
    });

    it("rendering component", () => {
        const props = {
            ...defaultProps,
        };

        const wrapper = shallow(<ExampleView {...props} />);
        const specificElement = wrapper.find(".specific-class-name");
        expect(specificElement.text()).to.be.equal(defaultProps.text);
    });
});
`

I think this is something related with `meteortesting:mocha` package and puppeteer, or maybe in between them. Here is the script I use to run unit tests on CI:

`
#!/bin/bash -eu

cd "$(dirname "${BASH_SOURCE[0]}")"/..

export PORT="${PORT:-5000}"
export ROOT_URL="http://localhost:${PORT}"
export TEST_BROWSER_DRIVER=puppeteer
export MOCHA_TIMEOUT=6000

cd node_modules/puppeteer/.local-chromium/linux-*/chrome-linux/
sudo chown root:root chrome_sandbox
sudo chmod 4755 chrome_sandbox
sudo cp -p chrome_sandbox /usr/local/sbin/chrome-devel-sandbox
export CHROME_DEVEL_SANDBOX=/usr/local/sbin/chrome-devel-sandbox
cd ../../../../../

meteor test --once --driver-package meteortesting:mocha --port "${PORT}" "$@"
`

I have tried with "-- --exit" in last command trying to force mocha to exit after all tests get done, but it does not help. Here is the list of versions I have:
meteor 1.8.3
node 8.17.0
puppeteer 1.20.0
meteortesting:browser-tests@1.3.1
meteortesting:mocha@1.1.3
meteortesting:mocha-core@6.2.2
react 16.12.0
sinon 7.5.0
chai 4.2.0
enzyme 3.10.0

Thanks in advance :)

### PR DESCRIPTION
**Pull request by make-github-pseudonymous-again**
I believe this should fix https://github.com/Meteor-Community-Packages/meteor-mocha/issues/104.

### CODE REVIEW

File: browser/puppeteer.js [hunk 1]
```diff
@@ -31,6 +33,7 @@ export default function startPuppeteer({
     const browser = await puppeteer.launch({
       args: ['--no-sandbox', '--disable-setuid-sandbox'],
       headless: 'new',
+      protocolTimeout: Number.parseInt(process.env.PUPPETEER_PROTOCOL_TIMEOUT, 10) || TWENTY_DAYS,
```
Comment (make-github-pseudonymous-again) [inline browser/puppeteer.js:36]: The env var name and the default value are derived from similar functionality already present for the `nightmare` driver: https://github.com/Meteor-Community-Packages/meteor-browser-tests/blob/72df7ffd5d76633a8469dbe42726d22453c7d8a2/browser/nightmare.js#L44

**Comment by make-github-pseudonymous-again** [comment]
@nachocodoner @jankapunkt @StorytellerCZ Will this require a backport to work in Meteor 2 or is the latest version compatible with both Meteor 2 and 3?

**Comment by jankapunkt** [comment]
@make-github-pseudonymous-again it's intended to work with both but please let me know if you encounter issues.

**Comment by make-github-pseudonymous-again** [comment]
@nachocodoner If that question is for me, I did not test anything. Just assumed it would work.

**Comment by make-github-pseudonymous-again** [comment]
@nachocodoner How could I test this before merging it? I can reproduce this bug locally.

**Comment by StorytellerCZ** [comment]
@make-github-pseudonymous-again create a `packages` folder in your app and in copy this package in there from the PR, that version will then take precedent.

**Comment by jankapunkt** [comment]
@make-github-pseudonymous-again cab there be a situation where users might want to set `protocolTimeout` to `0`?

**Comment by make-github-pseudonymous-again** [comment]
The `protocolTimeout` setting in `puppeteer` is a timeout that is applied to all registered connection message callbacks: if puppeteer does not get a message response within that time, then the connection is considered broken.

It seems the puppeteer driver implemented by Meteor is making puppeteer wait for a message response for the entire duration of the scheduled tests, which can easily reach in the minutes, especially for client app tests.

@jankapunkt `protocolTimeout = 0` would be interpreted as "no timeout" AFAICT. See:

  - https://github.com/puppeteer/puppeteer/blob/159513c8dbe2c9f51aa37dbe531d52b5daf1e106/packages/puppeteer-core/src/common/Connection.ts#L73-L82

Default is 3 minutes. See:

  - https://github.com/puppeteer/puppeteer/blob/159513c8dbe2c9f51aa37dbe531d52b5daf1e106/packages/puppeteer-core/src/common/Connection.ts#L202
  - https://github.com/puppeteer/puppeteer/blob/159513c8dbe2c9f51aa37dbe531d52b5daf1e106/packages/puppeteer-core/src/common/BrowserConnector.ts#L62-L67

File: browser/puppeteer.js (hunk 1 above)
Comment (jankapunkt) [inline browser/puppeteer.js]: @make-github-pseudonymous-again 

> protocolTimeout = 0 would be interpreted as "no timeout" AFAICT. See

In that case, your current code would never allow such, because 0 would be evaluated as falsy and thus always fall back to `TWENTY_DAYS`.

To also support 0 as value, it should be

```
protocolTimeout: process.env.PUPPETEER_PROTOCOL_TIMEOUT 
  ? Number.parseInt(process.env.PUPPETEER_PROTOCOL_TIMEOUT, 10) 
  : TWENTY_DAYS,
```

**Review by jankapunkt — CHANGES_REQUESTED** [review]

File: browser/puppeteer.js (hunk 1 above)
Comment (make-github-pseudonymous-again) [reply browser/puppeteer.js]: Makes sense.

Comment (make-github-pseudonymous-again) [reply browser/puppeteer.js]: On the other hand, the intention behind twenty days here (copied from Nightmare's default) is perhaps to disable the timeout entirely. So should we instead have the default be `0` instead of `TWENTY_DAYS`?

Comment (jankapunkt) [reply browser/puppeteer.js]: @StorytellerCZ what do you think here?

Comment (StorytellerCZ) [reply browser/puppeteer.js]: I think `0` should disable timeout, I think that is the intention with this. If nothing is passed then use default.

Comment (make-github-pseudonymous-again) [reply browser/puppeteer.js]: OK. I'll update this PR to set "no timeout" as the default, which means passing `protocolTimeout = 0` to `puppeteer`.

Comment (StorytellerCZ) [reply browser/puppeteer.js]: That is not what I meant. From my understanding the default right now is `TWENTY_DAYS`, keep that if there is no input. If the input is something different, including `0`, then set it to that. So if the input is `0`, then timeout is zero = disabled.

Comment (make-github-pseudonymous-again) [reply browser/puppeteer.js]: OK. Had misunderstood. Will apply @jankapunkt's suggestion instead then.

**Comment by make-github-pseudonymous-again** [comment]
> @make-github-pseudonymous-again create a `packages` folder in your app and in copy this package in there from the PR, that version will then take precedent.

@StorytellerCZ Just tested this. Works: setting a small timeout (5000ms) crashes mid-tests, setting a large timeout lets all tests run to completion. Setting a really small timeout (5ms) crashes during puppeteer setup.

Just out of curiosity, does it matter what name I give to the package under `packages/`? I named it `packages/meteortesting:browser-tests`.

Next step is to act on https://github.com/Meteor-Community-Packages/meteor-browser-tests/pull/58#discussion_r1891104026, and then I think it will be ready to merge.

**Comment by jankapunkt** [comment]
The folder name is irrelevant as long as it contains the package.js file with proper package config

File: browser/puppeteer.js (hunk 1 above)
Comment (make-github-pseudonymous-again) [reply browser/puppeteer.js]: Suggestion applied.

Comment (make-github-pseudonymous-again) [reply browser/puppeteer.js]: @StorytellerCZ Waiting for your input.

**Review by StorytellerCZ — APPROVED** [review]

**Review by jankapunkt — APPROVED** [review]
